# Generated by Django 5.0.4 on 2024-04-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_productimages_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="life",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="mfd",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_count",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, null=True
            ),
        ),
    ]
